spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: Lx>RwServer159
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      
logging:
  level:
    org:
      hibernate:
        type: trace